language: c++
compiler: gcc
os: linux

sudo: required

before_install:
    - sudo apt-add-repository 'deb http://ppa.launchpad.net/anatol/tup/ubuntu precise main'
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo add-apt-repository ppa:boost-latest/ppa -y
    - sudo apt-get update
    - sudo apt-get install tup
    - sudo apt-get install g++-5
    - sudo apt-get install libboost1.55-all-dev

install: tup init

script: tup